# rss-filter configuration file explained:
#
# General file syntax: YAML, see http://en.wikipedia.org/wiki/YAML
#
# The file contains 3 lists:
#   sources 
#   taggers
#   exportFiles
#
# Entries in "sources" list corresponds to Java classes in 
#   org.dfotos.rssfilter.src and org.dfotos.rssfilter.src.custom
#   The "srcrss" (See SrcRss.java) represents an RSS/ATOM feed. Just specify a valid URL of the feed
#   The "custom" sources: they are using site-specific API or web scraping.
#   At the moment there are two "custom" sources: 
#      "workinstartups.com" (See SrcWorkinstartups.java)
#      "jobs.remotive.io" (See SrcJobsRemotiveIo.java)
#
# Entries in "taggers" list represent so-called "taggers"
#   At the moment only one tagger exist: the "lucenetagger".
#   The "lucenetagger" performs the Lucene query (see "query" property) and attaches the tag (as in tagName) to every result of the query
#   The Lucene query syntax description can be found here: 
#	https://lucene.apache.org/core/4_10_3/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#package_description
#   Note: all lucene "documents" in index contains 3 fields:
#	title - corresponds to <title> in RSS format
#	description - corresponds to <description> in RSS format
#	all - title+description combined. this is the default field
#
# Entries in "exportFiles" represent the output (usually the output file)
#   The "exportfile" filters the entries and writes them into the corresponding <name>.atom file
#   Filtering... 
#	
#
#
!config

sources: 
#- !srcrss
   # this site is in Russian. you can comment out it
   # name: dou.ua 
   # url: http://jobs.dou.ua/vacancies/feeds/?cities=%D0%9E%D0%B4%D0%B5%D1%81%D1%81%D0%B0
- !srcrss
   name: weworkremotely.com
   url: https://weworkremotely.com/categories/2/jobs.rss
- !srcrss
   name: stackoverflow.com
   url: http://careers.stackoverflow.com/jobs/feed?allowsremote=True
- !org.dfotos.rssfilter.src.custom.SrcWorkinstartups
   name: workinstartups.com
   url: http://workinstartups.com/job-board/api/api.php?action=getJobs&type=0&category=programmers&count=999&random=0&days_behind=60&response=json&city=0
- !srcrss
   name: jobmote
   url: http://jobmote.com/feed.rss
- !srcrss
   name: authenticjobs.com
   url: http://www.authenticjobs.com/rss/custom.php?terms=&type=1,3,5,2,6&cats=&onlyremote=1&location=
- !srcrss
   name: indeed.com-1
   url: http://rss.indeed.com/rss?q=Remote+Java+Developer
- !srcrss
   name: indeed.com-2
   url: http://rss.indeed.com/rss?q=java&l=Remote
- !srcrss
   name: indeed.co.uk-1
   url: http://www.indeed.co.uk/rss?q=Remote+Java+Developer
- !srcrss
   name: indeed.co.uk-2
   url: http://www.indeed.co.uk/rss?q=java&l=remote&radius=100
- !srcrss
   name: itflow.biz
   url: http://itflow.biz/?feed=job_feed&type=contract,freelance,full-time,part-time,temporary&location&job_categories&s&job_region=2430
- !srcrss
   name: smashingmagazine.com
   url: http://jobs.smashingmagazine.com/rss/all/programming
- !srcrss
   name: wfh.io
   url: https://www.wfh.io/categories/1/jobs.atom
- !srcrss
   name: jobs.github.com-1
   url: https://jobs.github.com/positions.atom?description=remote&location=
- !srcrss
   name: jobs.github.com-2
   url: https://jobs.github.com/positions.atom?description=anywhere&location=
- !srcrss
   name: simplyhired.com-3
   url: http://www.simplyhired.com/a/job-feed/rss/qa-Java/fjt-telecommute/fcz-3
#- !srcrss 
#   name: simplyhired.com-2
#   url: http://www.simplyhired.com/a/job-feed/rss/qa-Java/fjt-telecommute/fcz-2
#- !srcrss
#   name: simplyhired.com-1
#   url: http://www.simplyhired.com/a/job-feed/rss/qa-Java/fjt-telecommute/fcz-1
- !srcrss
   name: nomadjobs.io
   url: http://nomadjobs.io/remote-jobs.rss
#- !srcrss
#   name: virtualvocations.com
#   url: http://www.virtualvocations.com/jobs/q-telecommuting+java+jobs/rss
- !srcrss
   name: remotecoder.io
   url: http://feedpress.me/remotecoder
- !srcrss
   # this kimono scraper does not work as it should
   name: jobsremotely.com-kimono
   url: https://www.kimonolabs.com/api/rss/2uucfbi2?apikey=PpdWi07uouYSAwDY0VfPpFnFypG6W0ry
- !srcrss
   # this kimono scraper does not work as it should
   name: remotehackers.com-kimono
   url: https://www.kimonolabs.com/api/rss/a8n56jsq?apikey=PpdWi07uouYSAwDY0VfPpFnFypG6W0ry
- !org.dfotos.rssfilter.src.custom.SrcJobsRemotiveIo
   name: jobs.remotive.io
   url: http://jobs.remotive.io/
- !srcrss
   name: remoteworkhunt.com
   url: http://www.remoteworkhunt.com/feed

taggers: 
- !lucenetagger
   docPart: td
   tagName: remote
   query: "title:(remote OR anywhere OR \"from home\"~1 OR \"work at home\"~1 OR \"home based\"~1 OR telecommute OR online OR \"co-location\"~1 OR \"International\"~1 )"

- !lucenetagger
   tagName: remote
   query: "description:( \"full remote\"~1 OR \"fully remote\"~1 OR \"full-time remote\"~1 OR \"remote anywhere\"~1 OR \"Work from home\"~1 OR \"remote only\"~1 OR \"International Okay\"~3 OR \"International contractor\"~5 ) "

- !lucenetagger
   tagName: java
   query: "description:( \"java API\" OR \"java skills\"~1 OR \"core java\"~1 OR \"excellent java\"~1 )"

- !lucenetagger
   tagName: java
   query: "description:( JVM OR dropwizard OR lucene OR SpringMVC OR JMS OR JPA OR Hibernate OR Maven OR Struts OR RMI OR Servlet OR playframework OR tomcat OR jetty OR Weblogic OR JBoss OR Wildfire )"

- !lucenetagger
   tagName: java
   query: "title:java"

- !lucenetagger
   # the field name is not specified in the query: means we are searching in the "all" field
   tagName: backend
   query: "( \"server-side\"~1 OR \"data engineer\"~1 OR \"backend engineer\"~1 OR \"Backend Developer\"~1 OR  \"Backend Development\"~1 OR \"java backend\"~1 OR \"java server\"~1 OR \"high availability\"~1 OR \"highly available\"~ OR \"high available\"~1 OR \"high performance\"~1 OR \"highly transactional\"~1 OR \"distributed systems\"~1 OR \"distributed system\"~1 OR \"data structures\"~1 OR \"database design\"~1 OR \"high throughput\" )"

- !lucenetagger
   # this tag is not used at the moment
   tagName: java-senior
   query: "title:( \"java senior\"~1 OR \"Senior Software Engineer\"~1 OR \"Senior Engineer\"~1 OR \"Senior Java Engineer\"~1 OR \"Senior developer\"~1 OR \"Senior java developer\"~1 OR architect OR Principal OR lead )"

- !lucenetagger
   tagName: residents-only
   query: "title:(\"US/Canada Residents Only\"~1 OR \"Residents Only\"~1 OR \"citizens only\"~1 )"

- !lucenetagger
   tagName: bad-tech
   query: "title:( C# OR .NET OR Drupal OR javascript OR jQuery OR frontend OR angularjs OR emberjs OR grails OR mobile OR android OR iOS OR PHP OR Flash OR Ruby OR RubyOnRails OR Rails OR \"java front end\" OR \"java frontend\" OR \"in test\" OR \"Front-End Development\" OR \"Front-End Developer\" )"

- !lucenetagger
   tagName: bad-jobtitle
   query: "title:( Junior OR Internship )"


exportFiles: 
- !exportfile
   name: java-backend
   tagsNOT:
   - bad-tech
   - residents-only
   - bad-jobtitle
   tagsAND:
   - backend

- !exportfile
   name: java-remote
   tagsNOT:
   - bad-tech
   - residents-only
   - bad-jobtitle
   tagsAND:
   - java
    
